FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

RUN apk add --no-cache chromium nss freetype harfbuzz ca-certificates ttf-freefont

COPY server ./server

ENV API_PORT=3001
ENV FACEBOOK_BROWSER_EXECUTABLE_PATH=/usr/bin/chromium-browser
EXPOSE 3001

CMD ["node", "server/index.mjs"]
